services:
  postgres:
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=Password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user" ]
      interval: 5s
      timeout: 5s
      retries: 5
    image: postgres:latest
  redis:
    ports:
      - 6379:6379
    image: redis:alpine	
  chesshandler:
    build:
      context: ./src
    ports:
      - 5089:5089
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
